PART2_PROCESS_TREE:
  children:
  - children:
    - level: 2
      name: level2.1
      print: true
      token: ''
    level: 1
    name: level1.1
    print: false
    token: ca5b2d
  - children:
    - level: 2
      name: level2.2
      print: false
      token: ''
    - level: 2
      name: level2.3
      print: true
      token: ''
    level: 1
    name: level1.2
    print: true
    token: 134efd
  - children:
    - level: 2
      name: level2.4
      print: false
      token: ''
    level: 1
    name: level1.3
    print: true
    token: 0252a9
  - children:
    - level: 2
      name: level2.5
      print: true
      token: ''
    level: 1
    name: level1.4
    print: false
    token: e8ad5e
  level: 0
  name: level0
  print: true
  token: ca5b2d134efd0252a9e8ad5e
